// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqlJSVq0L5dhh8--JoEpEWuC6H7BdyWmw',
    appId: '1:883865588359:web:e5529784d468ba8716de22',
    messagingSenderId: '883865588359',
    projectId: 'tom-web-f32d2',
    authDomain: 'tom-web-f32d2.firebaseapp.com',
    storageBucket: 'tom-web-f32d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq2YUZhAZCV8UL3jHjjYUj5UjJ7FqgkF4',
    appId: '1:883865588359:android:69c1126ce6edf69416de22',
    messagingSenderId: '883865588359',
    projectId: 'tom-web-f32d2',
    storageBucket: 'tom-web-f32d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjusldC5cZYtTHIS2YtfMrpPyIElSluCY',
    appId: '1:883865588359:ios:45632d2ac6f9878f16de22',
    messagingSenderId: '883865588359',
    projectId: 'tom-web-f32d2',
    storageBucket: 'tom-web-f32d2.appspot.com',
    iosClientId: '883865588359-t1etp65e1b1bpccfdhn2s82ccbsea13j.apps.googleusercontent.com',
    iosBundleId: 'com.example.website',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjusldC5cZYtTHIS2YtfMrpPyIElSluCY',
    appId: '1:883865588359:ios:45632d2ac6f9878f16de22',
    messagingSenderId: '883865588359',
    projectId: 'tom-web-f32d2',
    storageBucket: 'tom-web-f32d2.appspot.com',
    iosClientId: '883865588359-t1etp65e1b1bpccfdhn2s82ccbsea13j.apps.googleusercontent.com',
    iosBundleId: 'com.example.website',
  );
}
